/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_tray_internal_impl_DisplayThread */

#ifndef _Included_org_jdesktop_jdic_tray_internal_impl_DisplayThread
#define _Included_org_jdesktop_jdic_tray_internal_impl_DisplayThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jdesktop_jdic_tray_internal_impl_DisplayThread_MIN_PRIORITY
#define org_jdesktop_jdic_tray_internal_impl_DisplayThread_MIN_PRIORITY 1L
#undef org_jdesktop_jdic_tray_internal_impl_DisplayThread_NORM_PRIORITY
#define org_jdesktop_jdic_tray_internal_impl_DisplayThread_NORM_PRIORITY 5L
#undef org_jdesktop_jdic_tray_internal_impl_DisplayThread_MAX_PRIORITY
#define org_jdesktop_jdic_tray_internal_impl_DisplayThread_MAX_PRIORITY 10L
/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_DisplayThread
 * Method:    eventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_DisplayThread_eventLoop
  (JNIEnv *, jclass);

/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_DisplayThread
 * Method:    initTray
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_DisplayThread_initTray
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
