/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_browser_WebBrowserUtil */

#ifndef _Included_org_jdesktop_jdic_browser_WebBrowserUtil
#define _Included_org_jdesktop_jdic_browser_WebBrowserUtil
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_jdesktop_jdic_browser_WebBrowserUtil
 * Method:    nativeGetBrowserPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_browser_WebBrowserUtil_nativeGetBrowserPath
  (JNIEnv *, jobject);

/*
 * Class:     org_jdesktop_jdic_browser_WebBrowserUtil
 * Method:    nativeSetEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_browser_WebBrowserUtil_nativeSetEnv
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
