/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper */

#ifndef _Included_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
#define _Included_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_CLASSES_ROOT
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_CLASSES_ROOT -2147483648L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_CURRENT_USER
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_CURRENT_USER -2147483647L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_LOCAL_MACHINE
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_LOCAL_MACHINE -2147483646L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_USERS
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_USERS -2147483645L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_CURRENT_CONFIG
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_HKEY_CURRENT_CONFIG -2147483643L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_SUCCESS
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_SUCCESS 0L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_FILE_NOT_FOUND
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_FILE_NOT_FOUND 2L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_ACCESS_DENIED
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_ACCESS_DENIED 5L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_ITEM_EXIST
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_ITEM_EXIST 0L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_ITEM_NOTEXIST
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_ITEM_NOTEXIST 9L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_MAX_KEY_LENGTH
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_MAX_KEY_LENGTH 255L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_MAX_VALUE_NAME_LENGTH
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_MAX_VALUE_NAME_LENGTH 255L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_OPENED_KEY_HANDLE
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_OPENED_KEY_HANDLE 0L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_CODE
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ERROR_CODE 1L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_SUBKEYS_NUMBER
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_SUBKEYS_NUMBER 0L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_VALUES_NUMBER
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_VALUES_NUMBER 2L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_DELETE
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_DELETE 65536L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_QUERY_VALUE
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_QUERY_VALUE 1L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_SET_VALUE
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_SET_VALUE 2L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_CREATE_SUB_KEY
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_CREATE_SUB_KEY 4L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_ENUMERATE_SUB_KEYS
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_ENUMERATE_SUB_KEYS 8L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_READ
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_READ 131097L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_WRITE
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_WRITE 131078L
#undef org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_ALL_ACCESS
#define org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_KEY_ALL_ACCESS 983103L
/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegOpenKey
 * Signature: (I[BI)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegOpenKey
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegCloseKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegCloseKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegCreateKeyEx
 * Signature: (I[B)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegCreateKeyEx
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegDeleteKey
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegDeleteKey
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegFlushKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegFlushKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegQueryValueEx
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegQueryValueEx
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegSetValueEx
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegSetValueEx
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegDeleteValue
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegDeleteValue
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegQueryInfoKey
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegQueryInfoKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegEnumKeyEx
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegEnumKeyEx
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    RegEnumValue
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_RegEnumValue
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    FindMimeFromData
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_FindMimeFromData
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper
 * Method:    ExpandEnvironmentStrings
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_WinRegistryWrapper_ExpandEnvironmentStrings
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
