/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_tray_internal_impl_WinSystemTrayService */

#ifndef _Included_org_jdesktop_jdic_tray_internal_impl_WinSystemTrayService
#define _Included_org_jdesktop_jdic_tray_internal_impl_WinSystemTrayService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_WinSystemTrayService
 * Method:    eventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_WinSystemTrayService_eventLoop
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_WinSystemTrayService_initTray
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
