/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_desktop_internal_impl_GnomeTrayAppletService */

#ifndef _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeTrayAppletService
#define _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeTrayAppletService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_GnomeTrayAppletService
 * Method:    createAppletWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_GnomeTrayAppletService_createAppletWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_GnomeTrayAppletService
 * Method:    getWidget
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_GnomeTrayAppletService_getWidget
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
