/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_fileutil_impl_MacOSXNativeFileUtil */

#ifndef _Included_org_jdesktop_jdic_fileutil_impl_MacOSXNativeFileUtil
#define _Included_org_jdesktop_jdic_fileutil_impl_MacOSXNativeFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_fileutil_impl_MacOSXNativeFileUtil
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_fileutil_impl_MacOSXNativeFileUtil_getFreeSpace
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_fileutil_impl_MacOSXNativeFileUtil
 * Method:    getTotalSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_fileutil_impl_MacOSXNativeFileUtil_getTotalSpace
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
