/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_fileutil_impl_MacOSXFileUtil */

#ifndef _Included_org_jdesktop_jdic_fileutil_impl_MacOSXFileUtil
#define _Included_org_jdesktop_jdic_fileutil_impl_MacOSXFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_fileutil_impl_MacOSXFileUtil
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_fileutil_impl_MacOSXFileUtil_getFreeSpace
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
