/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_fileutil_impl_Win32FileUtil */

#ifndef _Included_org_jdesktop_jdic_fileutil_impl_Win32FileUtil
#define _Included_org_jdesktop_jdic_fileutil_impl_Win32FileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_fileutil_impl_Win32FileUtil
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_jdesktop_jdic_fileutil_impl_Win32FileUtil_getFreeSpace
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jdesktop_jdic_fileutil_impl_Win32FileUtil
 * Method:    recycle
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_fileutil_impl_Win32FileUtil_recycle
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
