/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileUtil */

#ifndef _Included_FileUtil
#define _Included_FileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileUtil
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_FileUtil_getFreeSpace
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FileUtil
 * Method:    recycle
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_FileUtil_recycle
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
