/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_dock_internal_impl_UnixDockService */

#ifndef _Included_org_jdesktop_jdic_dock_internal_impl_UnixDockService
#define _Included_org_jdesktop_jdic_dock_internal_impl_UnixDockService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_dock_internal_impl_UnixDockService
 * Method:    createDockWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_dock_internal_impl_UnixDockService_createDockWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_jdesktop_jdic_dock_internal_impl_UnixDockService
 * Method:    getWidget
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_dock_internal_impl_UnixDockService_getWidget
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jdesktop_jdic_dock_internal_impl_UnixDockService
 * Method:    adjustSizeAndLocation
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_dock_internal_impl_UnixDockService_adjustSizeAndLocation
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_jdesktop_jdic_dock_internal_impl_UnixDockService
 * Method:    mapWindow
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_dock_internal_impl_UnixDockService_mapWindow
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_jdesktop_jdic_dock_internal_impl_UnixDockService
 * Method:    locateDock
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_dock_internal_impl_UnixDockService_locateDock
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_dock_internal_impl_UnixDockService
 * Method:    eventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_dock_internal_impl_UnixDockService_eventLoop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
