/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_icons_impl_XdgDirectory */

#ifndef _Included_org_jdesktop_jdic_icons_impl_XdgDirectory
#define _Included_org_jdesktop_jdic_icons_impl_XdgDirectory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_icons_impl_XdgDirectory
 * Method:    gConfInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_icons_impl_XdgDirectory_gConfInit
  (JNIEnv *, jclass);

/*
 * Class:     org_jdesktop_jdic_icons_impl_XdgDirectory
 * Method:    getEnvironmentVariable
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_icons_impl_XdgDirectory_getEnvironmentVariable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_icons_impl_XdgDirectory
 * Method:    getGconfValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_icons_impl_XdgDirectory_getGconfValue
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
