/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_misc_impl_WindowsAlerter */

#ifndef _Included_org_jdesktop_jdic_misc_impl_WinAlerter
#define _Included_org_jdesktop_jdic_misc_impl_WinAlerter
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _alerter */
/*
 * Class:     org_jdesktop_jdic_misc_impl_WindowsAlerter
 * Method:    alertW
 * Signature: (Ljava/awt/Container;)V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_misc_impl_WinAlerter_alertWindows
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jdesktop_jdic_misc_impl_WindowsAlerter
 * Method:    getBlinkRate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_misc_impl_WinAlerter_getBlinkRate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
