/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_misc_impl_WinWallpaper */

#ifndef _Included_org_jdesktop_jdic_misc_impl_WinWallpaper
#define _Included_org_jdesktop_jdic_misc_impl_WinWallpaper
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _miscLibraryLoaded */
/* Inaccessible static: _wallpaper */
/*
 * Class:     org_jdesktop_jdic_misc_impl_WinWallpaper
 * Method:    nativeSetWallpaper
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_misc_impl_WinWallpaper_nativeSetWallpaper
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
