/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_desktop_internal_impl_MacBrowserService */

#ifndef _Included_org_jdesktop_jdic_desktop_internal_impl_MacBrowserService
#define _Included_org_jdesktop_jdic_desktop_internal_impl_MacBrowserService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_MacBrowserService
 * Method:    nativeBrowseURL
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_MacBrowserService_nativeBrowseURL
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
