/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_desktop_internal_impl_MacLaunchService */

#ifndef _Included_org_jdesktop_jdic_desktop_internal_impl_MacLaunchService
#define _Included_org_jdesktop_jdic_desktop_internal_impl_MacLaunchService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_MacLaunchService
 * Method:    nativeOpenFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_MacLaunchService_nativeOpenFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_MacLaunchService
 * Method:    nativePrintFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_MacLaunchService_nativePrintFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
