/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_icons_impl_WinIconWrapper */

#ifndef _Included_org_jdesktop_jdic_icons_impl_WinIconWrapper
#define _Included_org_jdesktop_jdic_icons_impl_WinIconWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_icons_impl_WinIconWrapper
 * Method:    GetIcon
 * Signature: ([C)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_icons_impl_WinIconWrapper_GetIcon
  (JNIEnv *, jclass, jcharArray);

#ifdef __cplusplus
}
#endif
#endif

