/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_fileutil_impl_UnixNativeFileUtil */

#ifndef _Included_org_jdesktop_jdic_fileutil_impl_UnixNativeFileUtil
#define _Included_org_jdesktop_jdic_fileutil_impl_UnixNativeFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_fileutil_impl_UnixNativeFileUtil
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_fileutil_impl_UnixNativeFileUtil_getFreeSpace
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
