/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_systeminfo_SystemInfo */

#ifndef _Included_org_jdesktop_jdic_systeminfo_SystemInfo
#define _Included_org_jdesktop_jdic_systeminfo_SystemInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_systeminfo_SystemInfo
 * Method:    nativeGetSessionIdleTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_systeminfo_SystemInfo_nativeGetSessionIdleTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
