/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_packager_impl_WinMsiWrapper */

#ifndef _Included_org_jdesktop_jdic_packager_impl_WinMsiWrapper
#define _Included_org_jdesktop_jdic_packager_impl_WinMsiWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_CREATE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_CREATE 3L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_DIRECT
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_DIRECT 2L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_READONLY
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_READONLY 0L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_TRANSACT
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIDBOPEN_TRANSACT 1L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_SEEK
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_SEEK -1L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_REFRESH
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_REFRESH 0L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_INSERT
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_INSERT 1L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_UPDATE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_UPDATE 2L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_ASSIGN
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_ASSIGN 3L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_REPLACE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_REPLACE 4L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_MERGE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_MERGE 5L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_DELETE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_DELETE 6L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_INSERT_TEMPORARY
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_INSERT_TEMPORARY 7L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE 8L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE_NEW
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE_NEW 9L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE_FIELD
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE_FIELD 10L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE_DELETE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_MSIMODIFY_VALIDATE_DELETE 11L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_SUCCESS
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_SUCCESS 0L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_ACCESS_DENIED
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_ACCESS_DENIED 5L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_HANDLE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_HANDLE 6L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_DATA
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_DATA 13L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_PARAMETER
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_PARAMETER 87L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_OPEN_FAILED
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_OPEN_FAILED 110L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_BAD_PATHNAME
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_BAD_PATHNAME 161L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_NO_MORE_ITEMS
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_NO_MORE_ITEMS 259L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_HANDLE_STATE
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_INVALID_HANDLE_STATE 1609L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_BAD_QUERY_SYNTAX
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_BAD_QUERY_SYNTAX 1615L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_CREATE_FAILED
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_CREATE_FAILED 1631L
#undef org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_FUNCTION_FAILED
#define org_jdesktop_jdic_packager_impl_WinMsiWrapper_ERROR_FUNCTION_FAILED 1627L
/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiOpenDatabase
 * Signature: ([BI)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiOpenDatabase
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiDatabaseOpenView
 * Signature: (I[B)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiDatabaseOpenView
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiViewExecute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiViewExecute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiViewFetch
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiViewFetch
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiRecordGetString
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiRecordGetString
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiRecordSetString
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiRecordSetString
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiViewModify
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiViewModify
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiRecordGetFieldCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiRecordGetFieldCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiViewClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiViewClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiDatabaseCommit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiDatabaseCommit
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiCloseHandle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiCloseHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiRecordSetStream
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiRecordSetStream
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiRecordReadStream
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiRecordReadStream
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiGetSummaryInformation
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiGetSummaryInformation
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiSummaryInfoSetProperty
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiSummaryInfoSetProperty
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiSummaryInfoPersist
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiSummaryInfoPersist
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiCloseAllHandles
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiCloseAllHandles
  (JNIEnv *, jclass);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiDatabaseGenerateTransform
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiDatabaseGenerateTransform
(JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiCreateTransformSummaryInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiCreateTransformSummaryInfo
(JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    UpdateResourceData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_updateResourceData
(JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    UpdateResourceString
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_updateResourceString
(JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    genUUID
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_genUUID
  (JNIEnv *, jclass);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiCreateRecord
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiCreateRecord
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiDatabaseImport
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiDatabaseImport
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    MsiDatabaseApplyTransform
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_msiDatabaseApplyTransform
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_jdesktop_jdic_packager_impl_WinMsiWrapper
 * Method:    NativeCreateProcess
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_packager_impl_WinMsiWrapper_nativeCreateProcess
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
