/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_fileutil_impl_SolarisNativeFileUtil */

#ifndef _Included_org_jdesktop_jdic_fileutil_impl_SolarisNativeFileUtil
#define _Included_org_jdesktop_jdic_fileutil_impl_SolarisNativeFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_fileutil_impl_SolarisNativeFileUtil
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_fileutil_impl_SolarisNativeFileUtil_getFreeSpace
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
