/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_fileutil_SolarisNativeFileUtil */

#ifndef _Included_org_jdesktop_jdic_fileutil_SolarisNativeFileUtil
#define _Included_org_jdesktop_jdic_fileutil_SolarisNativeFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_fileutil_SolarisNativeFileUtil
 * Method:    getFreeSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_fileutil_SolarisNativeFileUtil_getFreeSpace
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jdesktop_jdic_fileutil_SolarisNativeFileUtil
 * Method:    getTotalSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_fileutil_SolarisNativeFileUtil_getTotalSpace
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jdesktop_jdic_fileutil_SolarisNativeFileUtil
 * Method:    findFirst
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_fileutil_SolarisNativeFileUtil_findFirst
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jdesktop_jdic_fileutil_SolarisNativeFileUtil
 * Method:    findNext
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_fileutil_SolarisNativeFileUtil_findNext
  (JNIEnv *, jobject);

/*
 * Class:     org_jdesktop_jdic_fileutil_SolarisNativeFileUtil
 * Method:    findClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_fileutil_SolarisNativeFileUtil_findClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
