/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_misc_impl_LinuxAlerter */

#ifndef _Included_org_jdesktop_jdic_misc_impl_LinuxAlerter
#define _Included_org_jdesktop_jdic_misc_impl_LinuxAlerter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_misc_impl_LinuxAlerter
 * Method:    setUrgencyHint
 * Signature: (Ljava/awt/Frame;Z)V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_misc_impl_LinuxAlerter_setUrgencyHint
  (JNIEnv *, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
