/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_desktop_internal_impl_GnomeBrowserService */

#ifndef _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeBrowserService
#define _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeBrowserService
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: RESERVED_TARGET_NAMES */
/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_GnomeBrowserService
 * Method:    nativeBrowseURL
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_GnomeBrowserService_nativeBrowseURL
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
