/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_tray_internal_impl_GnomeTrayIconService */

#ifndef _Included_org_jdesktop_jdic_tray_internal_impl_GnomeTrayIconService
#define _Included_org_jdesktop_jdic_tray_internal_impl_GnomeTrayIconService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
