/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper */

#ifndef _Included_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
#define _Included_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_get_mime_type
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1get_1mime_1type
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_mime_get_description
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1mime_1get_1description
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_mime_get_icon
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1mime_1get_1icon
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_mime_get_key_list
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1mime_1get_1key_1list
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_mime_get_value
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1mime_1get_1value
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_mime_get_default_application_command
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1mime_1get_1default_1application_1command
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_get_registered_mime_types
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1get_1registered_1mime_1types
  (JNIEnv *, jclass);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    gnome_vfs_mime_get_extensions_list
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_gnome_1vfs_1mime_1get_1extensions_1list
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_filetypes_internal_GnomeVfsWrapper_getenv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
