/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService */

#ifndef _Included_org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService
#define _Included_org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: winMap */
/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService
 * Method:    createAppletWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService_createAppletWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService
 * Method:    getWidget
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService_getWidget
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService
 * Method:    adjustSizeHints
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService_adjustSizeHints
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_GnomeTrayAppletService_dispose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
