/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_desktop_internal_impl_GnomeUtility */

#ifndef _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeUtility
#define _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_GnomeUtility
 * Method:    nativeGetDefaultMailerPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_GnomeUtility_nativeGetDefaultMailerPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
