/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_desktop_internal_impl_GnomeLaunchService */

#ifndef _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeLaunchService
#define _Included_org_jdesktop_jdic_desktop_internal_impl_GnomeLaunchService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_desktop_internal_impl_GnomeLaunchService
 * Method:    nativeOpenFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_desktop_internal_impl_GnomeLaunchService_nativeOpenFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
