/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService */

#ifndef _Included_org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService
#define _Included_org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService
 * Method:    locateSystemTray
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService_locateSystemTray
  (JNIEnv *, jclass);

/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService
 * Method:    eventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService_eventLoop
  (JNIEnv *, jclass);

/*
 * Class:     org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService
 * Method:    dockWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jdesktop_jdic_tray_internal_impl_GnomeSystemTrayService_dockWindow
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
