/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_browser_WebBrowser */

#ifndef _Included_org_jdesktop_jdic_browser_WebBrowser
#define _Included_org_jdesktop_jdic_browser_WebBrowser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_browser_WebBrowser
 * Method:    nativeGetWindow
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jdesktop_jdic_browser_WebBrowser_nativeGetWindow
  (JNIEnv *, jobject, jstring);
  
#ifdef __cplusplus
}
#endif
#endif
