/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jdesktop_jdic_browser_internal_WebBrowserUtil */

#ifndef _Included_org_jdesktop_jdic_browser_internal_WebBrowserUtil
#define _Included_org_jdesktop_jdic_browser_internal_WebBrowserUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jdesktop_jdic_browser_internal_WebBrowserUtil
 * Method:    nativeGetBrowserPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL 
Java_org_jdesktop_jdic_browser_internal_WebBrowserUtil_nativeGetBrowserPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
